---
title: "Statistik ÜB Test"
author: "furela"
date: "7.12.21"
output: 
  html_document: 
    toc: yes
    toc_float: true
---

```{r setup, include=FALSE}
# Ich habe hier ein paar Standardeinstellungen für dich vorgenommen
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Packages laden

```{r lade-packages2, message=FALSE}

# Ich habe die Packages bereits für dich  geladen
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(forcats)
library(DBI)
library(palmerpenguins)

```

# Tastaturkürzel

Ich habe hier nochmals die wichtigsten Tastaturkürzel für dich hinzugefügt

- **Einen neuen Code-chunk hinzufügen:** Ctrl + Alt + I
- **Code "Zeile für Zeile" innerhalb eines Code-chunks ausführen:** Ctrl + Enter
- **Den gesamten Code-chunk ausführen:** Ctrl + Shift + Enter
- **Die Pipe (%>%):** Ctrl + Shift + M
- **Der Zuweisungs-Operator (<-)**: Alt + -
## R Markdown



```{r daten-import}

# Ich habe die Daten hier für euch heruntergeladen und in dem Ordner "data" gespeichert.

# Daten importieren

# download_link <- "/Users/regulafuglistaler/Documents/Regula/StAZH_Arbeitsunterlagen/Testdaten definitiv/Master_JJJJ.csv"

# master <- read_delim(download_link, delim = ";",
                       #locale = locale(encoding = "ISO-8859-1")) 
# Daten lokal speichern

# (ehedaten, "data/ehedaten.csv")

```

```{r daten-laden}

read_csv("data/test3_2JJJJ.csv")
Master <- read_csv("data/test3_2JJJJ.csv")

```
